# Compiler flag presets for some frequently used compilers
if( CMAKE_Fortran_COMPILER_ID MATCHES GNU )
  ecbuild_add_fortran_flags( "-cpp -W -Wall -Wno-tabs -Wno-compare-reals -fdefault-real-8 -fdefault-double-8 -march=native -ffree-line-length-none -std=gnu -Werror=implicit-interface" )
  ecbuild_add_fortran_flags( "-funroll-all-loops -fno-f2c -Ofast -g -fbacktrace" BUILD RELEASE )
  ecbuild_add_fortran_flags( "-finit-real=snan -fcheck=all -fbacktrace -fno-f2c -O0 -g -ffpe-trap=invalid,zero,overflow" BUILD DEBUG )
elseif( CMAKE_Fortran_COMPILER_ID MATCHES Intel )
  ecbuild_add_fortran_flags( "-cpp -r8 -ftz" )
  ecbuild_add_fortran_flags( "-O3" BUILD RELEASE )
  ecbuild_add_fortran_flags( "-traceback -fpe1 -O0 -g -check all" BUILD DEBUG )
elseif( CMAKE_Fortran_COMPILER_ID MATCHES PGI|NVHPC )
  ecbuild_add_fortran_flags( "-Mpreprocess -Mr8 -Mfree" )
  ecbuild_add_fortran_flags( "-Ofast" BUILD RELEASE )
  ecbuild_add_fortran_flags( "-Minit-real=snan -traceback -O0 -g -ffpe-trap=invalid,zero,overflow" BUILD DEBUG )
elseif( CMAKE_Fortran_COMPILER_ID MATCHES Fujitsu )
  ecbuild_add_fortran_flags( "-Cpp -CcdRR8 -g -Koptmsg=2 -X03" )
  ecbuild_add_fortran_flags( "-Kfast -x 128" BUILD RELEASE )
  ecbuild_add_fortran_flags( "-Haefosux -O0" BUILD DEBUG )
endif()
